version: '3.8'

services:
  app:
    container_name: nestjs-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data
      - ./src:/app/src
  postgres:
    container_name: postgresdb
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    build:
      context: ./src/data
      dockerfile: Dockerfile
    networks:
      - network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgresdb']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/var/logs/postgresql

volumes:
  data:
  logs:

networks:
  network:
    driver: bridge
